site_name: PeakCompare Documentation
repo_url: https://github.com/sof202/PeakCompare
site_description: "Documentation for PeakCompare"
site_author: "Sam Fletcher"
copyright: "© 2024, Sam Fletcher"
theme:
  logo: logo.svg
  favicon: logo.svg
  name: material
  palette:
    scheme: slate
    primary: black
    accent: green
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

